/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arbolgot;

/**
 *
 * @author Nathaly
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B_arbol = new javax.swing.JButton();
        B_antepasados = new javax.swing.JButton();
        B_nombre = new javax.swing.JButton();
        B_generacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_arbol.setBackground(java.awt.Color.lightGray);
        B_arbol.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        B_arbol.setText("Mostrar Árbol");
        jPanel1.add(B_arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 150, 50));

        B_antepasados.setBackground(java.awt.Color.lightGray);
        B_antepasados.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        B_antepasados.setText("Antepasados");
        jPanel1.add(B_antepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 50));

        B_nombre.setBackground(java.awt.Color.lightGray);
        B_nombre.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        B_nombre.setText("Buscar por nombre ");
        jPanel1.add(B_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 50));

        B_generacion.setBackground(java.awt.Color.lightGray);
        B_generacion.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        B_generacion.setText("Generación");
        jPanel1.add(B_generacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/arbolgot/imagenes/mapagotbla.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 450));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_antepasados;
    private javax.swing.JButton B_arbol;
    private javax.swing.JButton B_generacion;
    private javax.swing.JButton B_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
