package interfaces;

import com.mycompany.arbolgot.Arbol;
import com.mycompany.arbolgot.Clicks;
import com.mycompany.arbolgot.Hash;
import com.mycompany.arbolgot.HashTable;
import com.mycompany.arbolgot.List;
import com.mycompany.arbolgot.Person;
import static interfaces.IFbuscarNombre.ht;
import static interfaces.IFbuscarNombre.persons;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author Nathaly
 */
public class IFtitulo extends javax.swing.JInternalFrame {

    static List persons;
    static HashTable ht;
    String nombre;

    /**
     * Creates new form IFgeneracion
     */
    public IFtitulo(List L) {
        initComponents();
        this.setSize(400, 300);
        this.setTitle("Titulos");
        this.persons = L;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jC_nombres = new javax.swing.JComboBox<>();
        jB_cargarNombres = new javax.swing.JButton();
        jB_cargarNombres1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("generaciones");

        jB_cargarNombres.setText("cargar");
        jB_cargarNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cargarNombresActionPerformed(evt);
            }
        });

        jB_cargarNombres1.setText("ver");
        jB_cargarNombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cargarNombres1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_cargarNombres)
                            .addComponent(jB_cargarNombres1)
                            .addComponent(jC_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jC_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_cargarNombres)
                .addGap(18, 18, 18)
                .addComponent(jB_cargarNombres1)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cargarNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cargarNombresActionPerformed

        jC_nombres.removeAllItems();
        Person pAux = persons.getpFirst();
        
        List titles = new List();
        
        while (pAux != null) {
            if (pAux.getTitulo()!=null){
                
                 System.out.println(pAux.getName());
                    jC_nombres.addItem(pAux.getTitulo());

            }
            

            pAux = pAux.getNext();
        }

    }//GEN-LAST:event_jB_cargarNombresActionPerformed

    private void jB_cargarNombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cargarNombres1ActionPerformed

        Arbol arbol = new Arbol();
        arbol.Graph(persons);

        Clicks clicks = new Clicks();
        clicks.setGraph(arbol.getGraph());
        clicks.setViewer(arbol.getViewer());
        clicks.setPersons(persons);
        ht = arbol.getHashTable();
        clicks.setHt(ht);
        clicks.Clicks1();

        Object h = jC_nombres.getSelectedItem();
        String a = h.toString();
        String nums = a.replaceAll("[^0-9]", "");
        System.out.println(nums);

        Hash x = ht.serchHashTable(Integer.parseInt(nums));
        Person persona = x.getData();

        Graph grafo = arbol.getGraph();
        arbol.getGraph().getNode(Integer.toString(persona.getIndex())).setAttribute("ui.class", "shown");

        List descendants = new List();
        descendants = persona.getDesenders(descendants);

        for (int i = 1; i <= persons.getlen(); i++) {
            Person aux = persons.getPerson(i);
            
            arbol.getGraph().getNode(Integer.toString(aux.getIndex())).removeAttribute("ui.class");
            arbol.getGraph().getNode(Integer.toString(aux.getIndex())).removeAttribute("Thruth?");
        }
        for (int i = 1; i <= descendants.getlen(); i++) {
            Person aux = descendants.getPerson(i);
            arbol.getGraph().getNode(Integer.toString(aux.getIndex())).setAttribute("ui.class", "shown");
            arbol.getGraph().getNode(Integer.toString(aux.getIndex())).setAttribute("Thruth?");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cargarNombres1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cargarNombres;
    private javax.swing.JButton jB_cargarNombres1;
    private javax.swing.JComboBox<String> jC_nombres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
